// 🔥 GENERATED FILE: DO NOT EDIT 🔥
//
// This file is generated by lib/scripts/utils/gen_env_config.sh
// It contains all environment-specific variables for the app.
import 'dart:convert';

// Version info

class EnvConfig {
  static const String versionName =
      String.fromEnvironment('VERSION_NAME', defaultValue: '1.0.18');
  static const String versionCode =
      String.fromEnvironment('VERSION_CODE', defaultValue: '25');

// Keystore config
  static const String keyStoreUrl = String.fromEnvironment('KEY_STORE',
      defaultValue:
          'https://raw.githubusercontent.com/prasanna91/QuikApp/main/keystore.jks');
  static const String cmKeystorePassword =
      String.fromEnvironment('CM_KEYSTORE_PASSWORD', defaultValue: 'opeN@1234');
  static const String cmKeyAlias =
      String.fromEnvironment('CM_KEY_ALIAS', defaultValue: 'my_key_alias');
  static const String cmKeyPassword =
      String.fromEnvironment('CM_KEY_PASSWORD', defaultValue: 'opeN@1234');

// App info
  static const String appName =
      String.fromEnvironment('APP_NAME', defaultValue: 'Pixaware App');
  static const String orgName =
      String.fromEnvironment('ORG_NAME', defaultValue: 'Pixaware Technologys');
  static const String packageName =
      String.fromEnvironment('PKG_NAME', defaultValue: 'co.pixaware.Pixaware');

// Firebase config
  static const String firebaseConfigAndroid = String.fromEnvironment(
      'FIREBASE_CONFIG_ANDROID',
      defaultValue:
          'https://raw.githubusercontent.com/prasanna91/QuikApp/main/google-services-pw.json');
  static const String firebaseConfigIos = String.fromEnvironment(
      'FIREBASE_CONFIG_IOS',
      defaultValue:
          'https://raw.githubusercontent.com/prasanna91/QuikApp/main/GoogleService-Info-pw.plist');
  static const String apnsKeyId =
      String.fromEnvironment('APNS_KEY_ID', defaultValue: '2W22S6AY3Q');
  static const String apnsTeamId =
      String.fromEnvironment('APPLE_TEAM_ID', defaultValue: '9H2AD7NQ49');
  static const String apnsAuthKeyUrl = String.fromEnvironment(
      'APNS_AUTH_KEY_URL',
      defaultValue:
          'https://raw.githubusercontent.com/prasanna91/QuikApp/main/AuthKey_2W22S6AY3Q.p8');

// General
  static const String webUrl =
      String.fromEnvironment('WEB_URL', defaultValue: 'https://pixaware.co/');
  static const String emailId = String.fromEnvironment('EMAIL_ID',
      defaultValue: 'prasannasrie@gmail.com');

// Splash screen
  static const bool isSplashEnabled =
      bool.fromEnvironment('IS_SPLASH', defaultValue: true);
  static const String splashBgUrl =
      String.fromEnvironment('SPLASH_BG_URL', defaultValue: '');
  static const String splashUrl = String.fromEnvironment('SPLASH_URL',
      defaultValue:
          'https://raw.githubusercontent.com/prasanna91/QuikApp/main/pw-logo.png');
  static const String splashTagline = String.fromEnvironment('SPLASH_TAGLINE',
      defaultValue: 'Welcome to Pixaware');
  static const String splashTaglineColor =
      String.fromEnvironment('SPLASH_TAGLINE_COLOR', defaultValue: '#E91E63');
  static const String splashAnimation =
      String.fromEnvironment('SPLASH_ANIMATION', defaultValue: 'fade');
  static const int splashDuration =
      int.fromEnvironment('SPLASH_DURATION', defaultValue: 3);
  static const String splashBgColor =
      String.fromEnvironment('SPLASH_BG_COLOR', defaultValue: '#cfc3ba');

// Pull down
  static const bool isPullDown =
      bool.fromEnvironment('IS_PULLDOWN', defaultValue: true);

// Logo
  static const String logoUrl = String.fromEnvironment('LOGO_URL',
      defaultValue:
          'https://raw.githubusercontent.com/prasanna91/QuikApp/main/pw-logo.png');

// Deep linking
  static const bool isDomainUrl =
      bool.fromEnvironment('IS_DOMAIN_URL', defaultValue: true);

// Loading indicator
  static const bool isLoadIndicator =
      bool.fromEnvironment('IS_LOAD_IND', defaultValue: true);

// Permissions
  static const bool isCameraEnabled =
      bool.fromEnvironment('IS_CAMERA', defaultValue: false);
  static const bool isLocationEnabled =
      bool.fromEnvironment('IS_LOCATION', defaultValue: false);
  static const bool isMicEnabled =
      bool.fromEnvironment('IS_MIC', defaultValue: true);
  static const bool isNotificationEnabled =
      bool.fromEnvironment('IS_NOTIFICATION', defaultValue: true);
  static const bool isContactEnabled =
      bool.fromEnvironment('IS_CONTACT', defaultValue: false);
  static const bool isBiometricEnabled =
      bool.fromEnvironment('IS_BIOMETRIC', defaultValue: false);
  static const bool isCalendarEnabled =
      bool.fromEnvironment('IS_CALENDAR', defaultValue: false);
  static const bool isStorageEnabled =
      bool.fromEnvironment('IS_STORAGE', defaultValue: true);

// Push notification
  static const bool pushNotify =
      bool.fromEnvironment('PUSH_NOTIFY', defaultValue: false);

// Bottom menu
  static const bool isBottomMenu =
      bool.fromEnvironment('IS_BOTTOMMENU', defaultValue: true);
  static const String bottomMenuItems = String.fromEnvironment(
    'BOTTOMMENU_ITEMS',
    defaultValue:
        '[{"label":"Home","icon":{"type":"preset","name":"home_outlined"},"url":"https://pixaware.co/"},{"label":"services","icon":{"type":"custom","icon_url":"https://raw.githubusercontent.com/prasanna91/QuikApp/main/card.svg","icon_size":"24"},"url":"https://pixaware.co/solutions/"},{"label":"About","icon":{"type":"custom","icon_url":"https://raw.githubusercontent.com/prasanna91/QuikApp/main/about.svg","icon_size":"24"},"url":"https://pixaware.co/who-we-are/"},{"label":"Contact","icon":{"type":"custom","icon_url":"https://raw.githubusercontent.com/prasanna91/QuikApp/main/contact.svg","icon_size":"24"},"url":"https://pixaware.co/lets-talk/"}]',
  );

  static const String bottomMenuBgColor =
      String.fromEnvironment('BOTTOMMENU_BG_COLOR', defaultValue: '#f0f0e0');
  static const String bottomMenuIconColor =
      String.fromEnvironment('BOTTOMMENU_ICON_COLOR', defaultValue: '#888888');
  static const String bottomMenuTextColor =
      String.fromEnvironment('BOTTOMMENU_TEXT_COLOR', defaultValue: '#000000');
  static const String bottomMenuActiveTabColor = String.fromEnvironment(
      'BOTTOMMENU_ACTIVE_TAB_COLOR',
      defaultValue: '#FF2D55');
  static const String bottomMenuIconPosition =
      String.fromEnvironment('BOTTOMMENU_ICON_POSITION', defaultValue: 'above');
  static const String bottomMenuVisibleOn = String.fromEnvironment(
      'BOTTOMMENU_VISIBLE_ON',
      defaultValue: 'home,settings,profile');

// Bottom menu font styling (new)
  static const String bottomMenuFont =
      String.fromEnvironment('BOTTOMMENU_FONT', defaultValue: 'Montserrat');
  static double get bottomMenuFontSize =>
      double.tryParse(
          String.fromEnvironment('BOTTOMMENU_FONT_SIZE', defaultValue: '12')) ??
      12.0;
  static bool get bottomMenuFontBold =>
      String.fromEnvironment('BOTTOMMENU_FONT_BOLD', defaultValue: 'false')
          .toLowerCase() ==
      'true';
  static bool get bottomMenuFontItalic =>
      String.fromEnvironment('BOTTOMMENU_FONT_ITALIC', defaultValue: 'false')
          .toLowerCase() ==
      'true';

  // App Metadata
  // static const String appId = "";
  // static const String versionName = "1.0.0";
  // static const int versionCode = 1;
  // static const String appName = "QuikApp";
  // static const String orgName = "";
  // static const String webUrl = "google.com";
  // static const String userName = "";
  // static const String emailId = "";
  static const String branch = "main";
  static const String workflowId = "";

  // // Package Identifiers
  // static const String pkgName = "";
  // static const String bundleId = "";
  //
  // // Feature Flags (converted to bool)
  // static const bool pushNotify = false;
  // static const bool isChatbot = false;
  // static const bool isDomainUrl = false;
  // static const bool isSplash = true;
  // static const bool isPulldown = true;
  // static const bool isBottommenu = true;
  // static const bool isLoadIndicator = true;

  // Permissions (converted to bool)
  // static const bool isCamera = false;
  // static const bool isLocation = false;
  // static const bool isMic = false;
  // static const bool isNotification = false;
  // static const bool isContact = false;
  // static const bool isBiometric = false;
  // static const bool isCalendar = false;
  // static const bool isStorage = false;

  // // UI/Branding
  // static const String logoUrl = "";
  // static const String splashUrl = "";
  // static const String splashBg = "";
  // static const String splashBgColor = "#FFFFFF";
  // static const String splashTagline = "";
  // static const String splashTaglineColor = "#000000";
  // static const String splashAnimation = "none";
  // static const int splashDuration = 3;

  // Bottom Menu Configuration
  // static const String bottommenuItems = """[]""";
  // static const String bottommenuBgColor = "#FFFFFF";
  // static const String bottommenuIconColor = "#000000";
  // static const String bottommenuTextColor = "#000000";
  // static const String bottommenuFont = "DM Sans";
  // static const double bottommenuFontSize = 14.0;

  // Additional properties needed by the code (aliases for compatibility)
  static const bool isSplash = isSplashEnabled;
  static const String splashBg = splashBgUrl;
  static const bool isBottommenu = isBottomMenu;
  static const String bottommenuItems = bottomMenuItems;
  static const String bottommenuBgColor = bottomMenuBgColor;
  static const String bottommenuActiveTabColor = bottomMenuActiveTabColor;
  static const String bottommenuTextColor = bottomMenuTextColor;
  static const String bottommenuIconColor = bottomMenuIconColor;
  static const String bottommenuIconPosition = bottomMenuIconPosition;
  static const bool isCamera = isCameraEnabled;
  static const bool isLocation = isLocationEnabled;
  static const bool isMic = isMicEnabled;
  static const bool isNotification = isNotificationEnabled;
  static const bool isContact = isContactEnabled;
  static const bool isBiometric = isBiometricEnabled;
  static const bool isCalendar = isCalendarEnabled;
  static const bool isPulldown = isPullDown;
  static const String bottommenuFont = bottomMenuFont;
  static double get bottommenuFontSize => bottomMenuFontSize;
  static bool get bottommenuFontBold => bottomMenuFontBold;
  static bool get bottommenuFontItalic => bottomMenuFontItalic;

  // Chatbot property (missing from original)
  static const bool isChatbot =
      bool.fromEnvironment('IS_CHATBOT', defaultValue: false);

  // iOS Signing
  static const String appleTeamId = "";
  static const String certPassword = "";
  static const String profileUrl = "";
  static const String certP12Url = "";
  static const String certCerUrl = "";
  static const String certKeyUrl = "";
  static const String profileType = "app-store";
  static const String appStoreConnectKeyIdentifier = "";

  // Build Environment
  static const String buildId = "unknown";
  static const String buildDir = "";
  static const String projectRoot = "";
  static const String outputDir = "output";

  // Utility Methods
  static bool get isAndroidBuild => workflowId.startsWith('android');
  static bool get isIosBuild => workflowId.contains('ios');
  static bool get isCombinedBuild => workflowId == 'combined';
  static bool get hasFirebase =>
      firebaseConfigAndroid.isNotEmpty || firebaseConfigIos.isNotEmpty;
  static bool get hasKeystore => keyStoreUrl.isNotEmpty;
  static bool get hasIosSigning =>
      certPassword.isNotEmpty && profileUrl.isNotEmpty;
}
